version: '3'
services:
  example-name:
    build:
      context: .
      dockerfile: Dockerfile
    image: example-image:0.0.2
    container_name: example-name
    restart: always
    ports:
    - "0.0.0.0:5001:5000"
    user: "1002:1002"
    environment:
     - CONTAINERENV=False
     - PYTHINBUFFERED=False
    volumes:
      - ./container-data:/data
    networks:
      - main


version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '0.0.0.0:6380:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
    networks:
      - main
volumes:
  cache:
    driver: local



